name: CI / Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set compute/zone ${{ secrets.GCP_ZONE }}

      - name: Build and push image
        run: |
          IMAGE=${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/demo-repo/demo-app:${{ github.sha }}

          docker build -t $IMAGE ./app
          docker push $IMAGE

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT }}

      - name: Deploy to GKE
        run: |
          sed -i "s|gcr.io/REPLACE_WITH_PROJECT_ID/demo-app:\${GITHUB_SHA}|us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/demo-repo/demo-app:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
